Added description Correcting implementation of BaseTest and correction in PetStoreTests.java
New dependencies were added to fix issue
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
with java version higher than 1.8

README.md updated